# Generated by Django 3.0.8 on 2020-07-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_drafts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_time'], 'verbose_name': 'Paylaşım', 'verbose_name_plural': 'Paylaşımlar'},
        ),
    ]
