# Generated by Django 3.0.8 on 2020-07-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200705_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time'], 'verbose_name': 'Paylaşım', 'verbose_name_plural': 'Paylaşımlar'},
        ),
    ]
