# Generated by Django 3.0.8 on 2020-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugfy',
            field=models.SlugField(default=False, editable=False, max_length=123),
        ),
    ]
