# Generated by Django 3.0.8 on 2020-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_slugfy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugfy',
            field=models.SlugField(default='salam', editable=False, max_length=123, unique=True),
            preserve_default=False,
        ),
    ]
